use air_supply;

CREATE SCHEMA AIR_SUPPLY;

CREATE TABLE MAIN(
ORDER_ID INT,
LINE_NUMBER smallint,
VENDOR_ID Smallint,
PRODUCT_ID smallint,
ORDER_QUANTITY numeric(7,2), 
PRIMARY KEY (ORDER_ID, LINE_NUMBER),
FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR(VENDOR_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID));

CREATE TABLE VENDOR(
VENDOR_ID smallint,
VENDOR_NAME varchar(50),
ACCOUNTS_PAYABLE_TERMS smallint,
PRIMARY KEY (VENDOR_ID));

CREATE TABLE PRODUCT(
PRODUCT_ID smallint,
PRODUCT_NAME varchar(50),
PRODUCT_DESCRIPTION varchar(50),
PRODUCT_PRICE numeric(7,2),
PRIMARY KEY (PRODUCT_ID));

CREATE TABLE ORDER_DATE(
ORDER_ID INT,
ORDER_DATE DATE,
ARRIVAL_DATE DATE,
PRIMARY KEY(ORDER_ID),
FOREIGN KEY (ORDER_ID) REFERENCES MAIN(ORDER_ID));