CREATE INDEX index_prod_sku ON lgproduct (prod_sku);

ALTER TABLE LGINVOICE DROP FOREIGN KEY fk4;

ALTER TABLE LGINVOICE DROP FOREIGN KEY fk5;

ALTER TABLE LGPRODUCT DROP INDEX indexprod_sku;

SELECT * FROM lginvoice;